name: freelance_task
description: My Freelance Task.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  persistent_bottom_nav_bar: ^5.0.2
  get_storage: ^2.1.1
  sizer: ^2.0.15
  fl_chart: ^0.62.0
  circular_chart_flutter: ^0.0.2
  animated_button_bar:
    git:
      url: https://github.com/izart1994/animated_button_bar.git
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon_app.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
